version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: ultittt-server
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    env_file:
      - ./server/.env
    # overwrite some variables for local development
    environment:
      - DATABASE_URL=mongodb://db:27017/mydatabase?replicaSet=rs0&directConnection=false
      - DOMAIN_URL=http://localhost:5173
      - ENV=development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - ultittt-network

  db:
    image: mongo:7.0.21
    container_name: ultittt-mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet /scripts/replica-set.js"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./scripts:/scripts
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile:ro
    command: mongod --bind_ip_all --replSet rs0
    networks:
      - ultittt-network

  redis:
    image: redis:latest
    container_name: ultittt-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - ultittt-network

  client:
    build:
      context: ./client
#      args:
#        VITE_API_URL: "http://localhost:5000"
    container_name: ultittt-client
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_ENV=development
    ports:
      - '5173:5173'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - ultittt-network

networks:
  ultittt-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
