ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - bcrypt
  - prisma
